export const LOAD_CATEGORY_SUCCESS = "LOAD_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CARD_DRAG_AND_DROP_SUCCESS = "CARD_DRAG_AND_DROP_SUCCESS";
export const CREATE_TASK_CATEGORY_SUCCESS = "CREATE_TASK_CATEGORY_SUCCESS";
